language: ruby

services:
  - docker

env:
  matrix:
    - TAG=3.7
    - TAG=3.7-alpine
    - TAG=3.7-buster
    - TAG=3.7-slim
    - TAG=3.7-slim-stretch
    - TAG=3.7-stretch
    - TAG=3.8-slim
    - TAG=3.9-buster
    - TAG=3.9-slim
    - TAG=3.10-rc-buster

script:
  - sh build.sh ${TAG}

after_script:
  - docker images
